### ISSUE TITLE
Issue with VirtualService allowCredentials attribute in http corsPolicy object

### ISSUE THREAD

**Issue by AndreaNicola** [snowdrop/istio-java-api#119]
Hello, 

i'm having an issue trying to generate a VirtualService yaml with cors Policy, particularly with allowCredentials field.

Using this code:

```
System.out.println(Serialization.asYaml(new CorsPolicyBuilder()
                    .withNewAllowCredentials(true)
                    .withAllowMethods("GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS")
                    .withAllowOrigins(new StringMatchBuilder().withNewExactMatchType("*").build())
                    .withAllowHeaders("*")
                    .withNewMaxAge().withSeconds(24L * 60 * 60).endMaxAge()
                    .build()));
```

or this code

```
System.out.println(Serialization.asYaml(new CorsPolicyBuilder()
                    .withNewAllowCredentialsLike(new BoolValueBuilder().withNewValue(true).build()).endAllowCredentials()
                    .withAllowMethods("GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS")
                    .withAllowOrigins(new StringMatchBuilder().withNewExactMatchType("*").build())
                    .withAllowHeaders("*")
                    .withNewMaxAge().withSeconds(24L * 60 * 60).endMaxAge()
                    .build()));
```

i'm getting cors policy object looking like this:

```
allowCredentials:
  value: true
allowHeaders:
- "*"
allowMethods:
- "GET"
- "POST"
- "PUT"
- "DELETE"
- "PATCH"
- "OPTIONS"
allowOrigins:
- exact: "*"
maxAge: "86400s"
```

And when i try to use this cors policy with a virtualservice like the one below i got this error:

```
apiVersion: "networking.istio.io/v1beta1"
kind: "VirtualService"
metadata:
  labels:
    tenant: "pippo"
    app: "top-man-serv"
  name: "top-man-serv"
  namespace: "pippo"
spec:
  gateways:
  - "pippo"
  hosts:
  - "www.test.local"
  http:
  - corsPolicy:
      allowCredentials:
        value: true
      allowHeaders:
      - "*"
      allowMethods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "PATCH"
      - "OPTIONS"
      allowOrigins:
      - exact: "*"
      maxAge: "86400s"
    match:
    - uri:
        prefix: "/topology"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: "top-man-serv"
        port:
          number: 80
```

Message: VirtualService.networking.istio.io "top-man-serv" is invalid: spec.http.corsPolicy.allowCredentials: Invalid value: "object": spec.http.corsPolicy.allowCredentials in body must be of type boolean: "object". Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.http.corsPolicy.allowCredentials, message=Invalid value: "object": spec.http.corsPolicy.allowCredentials in body must be of type boolean: "object", reason=FieldValueInvalid, additionalProperties={})], group=networking.istio.io, kind=VirtualService, name=top-man-serv, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=VirtualService.networking.istio.io "top-man-serv" is invalid: spec.http.corsPolicy.allowCredentials: Invalid value: "object": spec.http.corsPolicy.allowCredentials in body must be of type boolean: "object", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).

Is it my fault or a cors policy object should look like this?

```
allowCredentials: true
allowHeaders:
- "*"
allowMethods:
- "GET"
- "POST"
- "PUT"
- "DELETE"
- "PATCH"
- "OPTIONS"
allowOrigins:
- exact: "*"
maxAge: "86400s"
```

Thanks!
