### ISSUE TITLE
Error parsing Policy YAML

### ISSUE THREAD

**Issue by geoand** [snowdrop/istio-java-api#48]
When attempting to parse the following:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: recommendation
  namespace: tutorial
spec:
  hosts:
  - recommendation
  http:
  - match:
    - headers:
        baggage-user-agent:
          regex: .*DarkLaunch.*
    route:
    - destination:
        host: recommendation
        subset: version-v2
  - route:
    - destination:
        host: recommendation
        subset: version-v1
```

via `mapper.readValue(inputStream, VirtualService.class)` we get the following error: https://gist.github.com/geoand/98395a190f83949407305ef6bed8f868
