### ISSUE TITLE
Lookup on http route in Virtualservice yaml is not working

### ISSUE THREAD

**Issue by naitikdani** [snowdrop/istio-java-api#68]
Hello @metacosm ,

I have this yaml file:

```
spec:
  gateways:
  - logforwarding-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: /onboard
    route:
    - destination:
        host: provision-service
        port:
          number: 9080
  - match:
    - headers:
        tenantid:
          exact: "coke"
    route:
    - destination:
        host: service-coke
        port:
          number: 8080
```

I want to do a lookup on http route with route/destination/host as `service-coke` and port 8080.

I wrote this code and it returned `false`:
```
Destination dst = new DestinationBuilder()
                    .withHost("service-coke")
                    .withPort(new PortSelector(new NumberPort(8080))).build();

            HTTPRouteDestination routeDst = new HTTPRouteDestinationBuilder()
                    .withDestination(dst).build();
            HTTPRoute route = new HTTPRouteBuilder().withRoute(routeDst).build();
            
boolean entryFound = istioClient.virtualService().inNamespace(istioClient.getNamespace())
                    .withName("logforwarding-virtualservice")
                    .get().getSpec().getHttp().contains(route);
```

I got `entryFound` as `false`.
Is this the right way to do a lookup for http route? 
Thanks in advance
